[package]
name = "jomini"
version = "0.1.0"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
edition = "2018"

[dependencies]
serde = "1"
memchr = "2"
byteorder = "1"
encoding_rs = "0.8"

[dev-dependencies]
jemallocator = "0.3"
criterion = "0.3"
quickcheck = "0.9"
quickcheck_macros = "0.9"
serde = { version = "1", features = ["derive"] }
zip = { version =  "0.5", default-features = false, features = ["deflate"] }

[[bench]]
name = "jomini_bench"
harness = false
