[package]
name = "jomini"
version = "0.1.0-pre"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
license = "MIT"
edition = "2018"
repository = "https://github.com/rakaly/jomini"
categories = ["parsing"]
description = "Low level, performance orientated parser for EU4 save files and other formats"
keywords = ["eu4", "ironman", "clausewitz"]

[workspace]
members = ["jomini_derive"]

[dependencies]
serde = { version = "1", optional = true }
jomini_derive = { path = "jomini_derive", version = "0.1.0-pre", optional = true }

# Make encoding_rs optional as it adds 150KB to the wasm bundle and the
# performance in real world tests didn't change
encoding_rs = { version = "0.8", optional = true }

[features]
default = ["derive"]
derive = ["serde", "jomini_derive"]

[dev-dependencies]
encoding_rs = "0.8"
criterion = "0.3"
quickcheck = "0.9"
quickcheck_macros = "0.9"
serde = { version = "1", features = ["derive"] }

[[bench]]
name = "jomini_bench"
harness = false

[profile.bench]
lto = true
codegen-units = 1

[profile.release]
lto = true
codegen-units = 1
