[package]
name = "jomini_derive"
version = "0.0.0"
edition = "2018"
publish = false

[lib]
proc-macro = true

[dev-dependencies]
trybuild = { version = "1.0", features = ["diff"] }
serde = "1"
serde_json = "1"

[dependencies]
syn = "1"
quote = "1"
