[package]
name = "jomini_derive"
version = "0.1.0-pre"
edition = "2018"

[lib]
proc-macro = true

[dev-dependencies]
trybuild = { version = "1.0", features = ["diff"] }
serde = "1"
serde_json = "1"

[dependencies]
syn = "1"
quote = "1"
